project:
  type: website
  output-dir: docs

website:
  title: "Deep Learning/Deep Ancestry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Articles"
        menu:
          - genome_size_intro.qmd       


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



